trezord.go
usb/bus.go
usb/udp.go
usb/webusb.go

This differs from this PR https://github.com/trezor/trezord-go/pull/9 in some ways
It is correctly handling turning off the emulator during the call. That is useful for testing states of user disconnecting the device. However, that adds a significant complexity, since some incoming packets "belong" to the detections and some "belong" to the reader, which is solved here by the channels.
Also, the emulators are not called by default, but only when a flag is present
`trezord-go -e 21324 -e 21326`
When there are no ports, the layer is not inited at all.

Add emulator/UDP

---

server/http.go

This solves issues with more connected devices

sessions: Always order devices by path

---

release/linux/fpm.before-install.sh

`/sbin/nologin` is located at `/usr/sbin/nologin` on Debian/Ubuntu systems and either way the shell should never be used so `/bin/false` is probably better (see https://unix.stackexchange.com/a/10867 for the difference between the two)

Fix trezord shell path (nologin -> false)

---

release/windows/release.sh

This is a very simple pull request to go along with the discussion in [this ticket](https://github.com/trezor/trezord-go/issues/42).
To sum up the findings : 
As it appears you are using authenticode in the background as part of osslsigncode the url parameter is all that is needed to generate a SHA256 timestamp, provided that the signing certificate was SHA256 as well.
If you are using the RFC 3161 timestamp a second parameter is needed in the request, /td, in which the algorithm is specified.

Added url parameter for /td <algorithm> switch from SignTool.

---

release/windows/Dockerfile.devcon
release/windows/Makefile
release/windows/devcon/cmds.cpp
release/windows/devcon/devcon.cpp
release/windows/devcon/devcon.h
release/windows/devcon/devcon.manifest.xml
release/windows/devcon/devcon.rc
release/windows/devcon/dump.cpp
release/windows/devcon/msg.mc
release/windows/devcon/rc_ids.h
release/windows/devcon/wildcard.cpp
release/windows/release.sh
release/windows/trezord.nsis
server/devcon.go
server/devcon_shim.go
server/http.go

This builds devcon - tool from Microsoft Driver Kit - and add it to installation.
It was necessary to do some changes in devcon, since MinGW (c++ cross-compiler) has some issues with printing wide strings and I was not able to fix the issues directly; so I just used wscombs to copy the strings to standard string and print those. (All the changes are in dump.cpp, compare to https://github.com/Microsoft/Windows-driver-samples/tree/master/setup/devcon )
What this PR also does:
* in the debug page, lists all Trezor devices in Device Manager, both connected and disconnected, both T1 and T2 (and all the sub-devices in composite device), plus  addresses of their driver files
* it also removes all remembered Trezor devices from the system on install (before WDI driver install)
* it also prevents …

Build and add devcon

---

README.md
server/http.go

Adding /post call, that never reads the response.
Useful for debug link. So far only works on UDP transport with emulator.

Adding /post call

---

memorywriter/memorywriter.go
server/devcon.go
server/devcon_shim.go
server/http.go
server/statustemplate.go
trezord.go
usb/hidapi.go
usb/webusb.go
wire/v1.go

To better diagnose USB issues, I have added very crazy detailed logging.
This logs are kept just in memory, just around 10MB of them, and they are offered for download at the status page (as gzip, done through golang gzip + javascript blob download link)

Add more detailed logs

---

release/windows/devcon/cmds.cpp
release/windows/trezord.nsis

Adding the functionality of removing all INF files (which "uninstalls" the driver) with a specific vendor to devcon, mostly by moving around pieces of code
Also using that added functionality in NSIS installer, AFTER removing the devices remove the drivers too. Also uninstalls drivers installed by Zadig tool that we recommended on support, but that is no longer needed.
Rescan is a voodoo that probably does nothing, but it might have helped on one testing notebook (not sure if it was placebo).

Deleting inf

---

release/macos/release.sh

Requires files extracted from certificate given by Apple, as described here
http://users.wfu.edu/cottrell/productsign/productsign_linux.html
Add files `cert00`, `cert01`, `cert02` and `key.pem` to release/macos/

macos: Sign the installer

---

memorywriter/memorywriter.go
usb/bus.go
usb/hidapi.go

From https://github.com/golang/go/wiki/CodeReviewComments#error-strings :
> Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use fmt.Errorf("something bad") not fmt.Errorf("Something bad"), so that log.Print("Reading %s: %v", filename, err) formats without a spurious capital letter mid-message. This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.

errors should not be capitalized

---

server/status/devcon.go
server/status/devcon_shim.go
server/status/status.go

Setupapi dev log is very powerful for letting us debug device driver issues for Windows 7, for example, why are HP BIDI drivers preferred from our drivers.

windows: add setupapidevlog to log

---

release/windows/trezord.nsis

Because of the installation of the first driver, the second driver never happened and immediately crashed in rare cases. (I found this issue only because of the new libwdi install logs.)
This adds a timeout of 2 minutes. (It should be enough - looking at the logs from the faulty system, the installation takes about 15 seconds).
This should hopefully fix the remaining driver issues.

libwdi: Add timeout to installer

---

usb/lowlevel/c/libusb/libusbi.h
usb/lowlevel/c/libusb/os/threads_windows.h
usb/lowlevel/c/libusb/os/windows_winusb.c
usb/lowlevel/hid.go
usb/lowlevel/libusb.go
usb/webusb.go

Libusb lists all devices, even those without drivers.
What can happen is that a user can open web wallet, connect a new device, and while the winusb driver is installing, the device is shown to wallet, which tries to immediately connect to it and errors. User sees libusb error and thinks something is broken (while reconnecting device would have actually helped).
So what we need to do is to exclude devices without winusb drivers in device listing.
I was too afraid to change the device listing in os/windows_winusb.c to exclude it directly there - because I was afraid of a memory leak (the memory is manually managed for the device objects).
Instead, I did a dirtier solution - I have added a field to the device struct that is by default 0 on both composite devices and "single" devices, but is …

windows libusb: show only winusb devices

---

usb/webusb.go

I *think* this happens only on Linux when disconnecting device while communication is going on.
Tested on Linux, the error is now more readable.

usb: read libusb error_pipe as disconnect error

---

usb/lowlevel/c/libusb/descriptor.c
usb/lowlevel/c/libusb/libusbi.h
usb/lowlevel/c/libusb/os/threads_windows.h
usb/lowlevel/hid.go
usb/lowlevel/libusb.go
usb/webusb.go

"Less intrusive" in that the libusb headers are not changed and included in go layer,
so other OS can use the default, system-wide one.
This returns the headers in the go files to the state before #90 
Fixes https://github.com/trezor/trezord-go/issues/94

windows: Less intrusive winusb check

---

core/core.go
usb/hidapi.go
usb/udp.go
usb/webusb.go

"Finishing reading queue" is necessary only because sometimes the handle is closed before the device sends all the USB packets, which happens only when one app "steals" device from another.
It is never necessary on disconnected devices; on the contrary, it sometimes causes issues. (On freebsd, for example.)
This requires a slight change in the device interface.

usb: Do not finish read queue on disconnected

---

release/windows/libwdi/libwdi/libwdi.c
release/windows/trezord.nsis

Right now, we wait for all other pending installation to finish before we start installing the driver, and if we time out, we don't install the driver.
I think it causes more issues than it solves. Let's try removing the wait, what happens.
See also discussion here
https://github.com/pbatard/libwdi/pull/140

windows: Remove wait for pending install

---

usb/lowlevel/c/libusb/libusb.h
usb/lowlevel/c/libusb/sync.c
usb/lowlevel/libusb.go
usb/webusb.go

The main reason why we used interrupt with timeouts is that we cannot cancel transfers, using the libusb synchronnous API.
However, the repeated timeouts cause issues with the bootloader for unknown reasons.
Instead of using timeouts, I added a function to cancel transfers to synch libusb API. Then we can safely remove the timeouts from the code, since we cancel the calls manually. (We cannot remove them completely - we still use them for finishing the read queue.)
What I did not know before is that using libusb close on a device with pending synch transfers **does not cancel the pending transfers** - and the transfers then hang forever! (Also, libusb device close is a non-blocking function.)
---
This is a little complex, but the other option would be to basically rewrite sync.c into go. …

libusb: Add cancel to sync.c, don't use timeouts

---

release/windows/libwdi/libwdi/installer.c
release/windows/libwdi/libwdi/libwdi.c

For some reason libwdi sometimes fails on driver preparation with emtpy error.
Add more logs for checking what is going on.
Also increase timeout for inter-process libwdi communication

More libwdi logs

---

core/core.go
server/http.go
trezord.go
usb/hidapi.go
usb/libusb.go
usb/lowlevel/hid.go
usb/webusb.go

I have done a small cleanup of OS-specific code.
tl;dr:
* On freebsd, do not allow session stealing, as it's too complex to do with system libusb.
* On freebsd and linux, use libusb even for the current HID trezor.
* rename webusb.go/WebUSB to libusb.go/LibUSB
---
The initial problem I was trying to solve is the 5-second timeouts still create issues on FreeBSD. 
---
To explain why do we need all this complicated machinery. For better user experience, we allow for "multitasking" - that is, applications can "steal" sessions from each other when device is in session, and that should cancel the communication. The result after "session stealing" should be a device that is capable of communication; after a session is stolen and after the stealing application calls an "initialize" message, the …

Cleanup of OS-specific (freebsd) code

---

release/windows/trezord.nsis

This is a pretty bad bug that prevented the drivers to be installed on the first install
The AppData/TREZOR Bridge was created only on the first run of bridge. The driver installation script failed, because it could not write its log anywhere.

windows7: create AppData before installing

---

core/core.go
server/api/api.go

Better version of #146 (I actually understand Context now :) )

core: Use idiomatic context, not struct channels

---

core/core.go

When built with `-race`, running acquire and then:
```
echo -n "001400000000" | http -v POST "127.0.0.1:21325/call/2"
```
(`001400000000` is just an example of Cancel message, http command is [httpie](https://httpie.org/), use whatever you want.)
following with a release command:
```
http -v POST "127.0.0.1:21325/release/2"
```
I am receiving a race condition warning as mentioned in https://github.com/trezor/trezord-go/issues/190#issuecomment-627142657. I believe that in some rare cases this could have led to a crash when two concurrent writes actually happened? In @mroz22's case (see the issue) it was concurrent iteration and write, so my guess is it was Acquire's `findPrevSession` and Release's `delete`.
----
This PR adds sessionsMutex lock to `release` so the calls are separated. …

Lock sessionsMutex when deleting session

---

README.md
core/debug.go
core/release.go
server/api/api.go
trezord.go

When build using `go build -tags debug` a debug mode is enabled. Currently that means disabling CORS, which is helpful for local development and when run inside a docker image.

Introduce debug build mode

---

.gitlab-ci.yml

Aded tests from travis ci to gitlab ci, for now only test are able to run on gitlab ci. Unfortunately no builds since xgo is not supported on gitlab without some hacking to the source.

migrated tests from travis 

---

release/linux/fpm.before-install.sh

As far as I'm aware, Linux has never logged to `/var/log/trezord.log` (I did a quick search through `git blame` and couldn't find anything).
Because of that, there's no reason to even create the `/var/log/trezord.log` file.
On my PC, `ls -lhrt /var/log/trezord.log` shows that it has 0 bytes, and has been unmodified since 2021. 
```console
user@computer:~$ sudo ls -lhrt /var/log/trezord.log 
-rw-rw---- 1 trezord trezord 0 Oct 17  2021 /var/log/trezord.log
```
Instead, Linux just relies on systemd's logger. On most new devices, you can view these logs via `journalctl -u trezord`.
I'm 99.9% sure this will fix #245 and fix #246, but I don't run Fedora or Fedora Silverblue, so it might be worth @hegjon or @triceo testing (if they're still interested)

fix(linux): remove /var/log/trezord.log creation

---

.gitlab-ci.yml

The golangci-lint job is failing on GitLab CI, see https://gitlab.com/satoshilabs/trezor/trezord-go/-/commit/ec928e6456bfa60c9a298ae78613f723db256900/pipelines?ref=master
This is because only v1.45.1 of golangci-lint supports golang v1.18.0, see https://github.com/golangci/golangci-lint-action/issues/434#issuecomment-1086127909
It's also possible to fix this bug by updating the `golangci-lint`, but that causes a bunch of warnings and errors, so it's probably easier to just keep the golang version at `v1.17`.

Fix failing CI by linting with golang v1.17

---

usb/libusb.go

The config descriptors from the libusb c-library are not being properly closed by the golang code.
On my PC, when testing with MetaMask, this causes an approximately 10 MB per hour memory leak. This memory leak is not detected via golang's  pprof, as it's in the c-library.
Closing these config descriptors using `defer` seems to fix this memory leak in my testing.
This seems to fix #223 (at least for me!). `trezord-go` now seems to pretty stable at around 50 MB.
In order to find this memory leak, I first added a `pprof` API call to `trezord-go`, which I used to get performance data on the golang heap and co-routine (let me know if you'd be interested in a PR for this too).
What I found was that according to `pprof`, there was no memory leak.
However, according to Linux, `trezord-go` was …

fix: close libusb config description memory leak

---

release/macos/Dockerfile
release/macos/Makefile
release/macos/build-fat.sh
release/macos/release.sh

xgo is deprecated. Let's replace it with Elastic's Golang-crossbuild.
It is better documented and more maintained.
https://github.com/elastic/golang-crossbuild
That docker conveniently also has lipo, which will make the fat binary.

Rework build, replace xgo with golang-crossbuild

---

.gitignore
release/macos/Dockerfile
release/macos/Makefile
release/macos/release.sh

I have simplified signing and enabled notarization in docker with rcodesign (a Rust-based tool, fully open-source; but it does connect to Apple servers for notarization).
This tool enables notarization and signing fully in Docker on any OS, so it should work in CLI too.
There is some prep-work that needs to be done on Mac OS side and on Apple website; but after that, the signing and notarization works automatically.
It's not directly relevant to this commit, but I think you can also use it on Trezor Suite; a cursory glance there tells me that Trezor Suit is using electron-notarize, which needs to be run on Mac OS; rcodesign does not need that.
Note that we need to use ldflags -s because of this issue of rcodesign - https://github.com/indygreg/PyOxidizer/issues/636

Simplify signing, enable notarization

---

Makefile
release/linux/Makefile
release/macos/Makefile
release/windows/Makefile
trezord.go

In go 1.18, go is "magically" putting git hash to binary itself, which can be read in the code itself. So we don't need the `git parse` in Makefiles.
(I actually forgot to put the GITHASH magic to the osx build, but better to fix it properly.)
The module version is _not_ put there, as it's hard to tell from just git. So we still need that there.

Remove githash from Makefiles, move to go code

---

release/linux/Dockerfile.build
release/linux/Dockerfile.package
release/linux/Makefile
release/linux/build.sh

When I tried to build with "normal" glibc, I got weird errors on old/new glibc.
Instead of building with glibc, which limits us with compatibility and weird issues, let's build with musl, which will always produce 100% static library.
(Musl is a libc alternative. The good thing is musl is statically linked and can cross-compile relatively easily.)
The actual hard work is building all these musl cross-compilers; luckily, Rust people already did that for Rust :) we can steal that and reuse.
Note that this all works on both AMD and ARM hosts, as both the musl cross-compilers images and the go images are published for both.

Build Linux binaries with musl

---

release/windows/Dockerfile.wdi_driver
release/windows/Makefile
release/windows/release.sh

This one was surprisingly easy.
Note that it still needs the authenticode certs to be signed on Windows. I don't know how to get them, so I didn't really add that to the shell script.

Fix windows build

---

release/linux/build.sh

The issue is with new git, and Linux Docker hosts.
It's a mitigation against CVE-2022-24765, as the owner of the outside repo needs to be the same as the current user; and the user inside the docker container is root. (Go is running git to do the version stamping.)
Simple fix is to add a safe directory, as the CVE does not apply to us.

Fix linux build for linux hosts

---

.gitignore
Makefile
release/Makefile
release/linux/release.sh
release/macos/Dockerfile
release/macos/release.sh
release/windows/Dockerfile
release/windows/release.sh

I have cleaned up the makefiles. I have also moved the GPG signing to the individual releases and out of existing Makefile.
Also I read the GPG key out of GPG instead of hard-coding it.
The negative is that now we require quite a lot of keys to set up... especially the macos now needs tons of keys.
I will try to document them all somewhere.

Clean makefiles, move GPG signing to release.sh

---

usb/lowlevel/libusb/libusb.go

There were 2 warnings, caused by libusb go code:
* on linux, use POSIX header instead of "incorrect" header that is redirected
* remove unused libusb set_debug from go code (as that caused deprecation warnings)
By the way. The original go library, that we used, is no longer maintained; but it's just a thin wrapper around libusb itself.

Remove warnings caused by libusb go code

---

release/windows/Makefile

That's a cygwin flag for SDK version. I am not 100% sure if it's necessary, but it shuts up the warnings, so let's do it.

Fix windows warning by adding Win 7 WIN32_WINNT

---

Dockerfile

**Problem:**
The current Dockerfile doesn't work when building the image. Consequently, the Docker compose file also doesn't work. This problem is caused by following issues.
1. The latest go version (1.21) can't compile the source file `usb/lowlevel/libusb/libusb.go` with these error messages.
```sh
usb/lowlevel/libusb/libusb.go:405:10: cannot define new methods on non-local type *C.struct_libusb_endpoint_descriptor
usb/lowlevel/libusb/libusb.go:455:10: cannot define new methods on non-local type *C.struct_libusb_interface_descriptor
usb/lowlevel/libusb/libusb.go:510:10: cannot define new methods on non-local type *C.struct_libusb_interface
usb/lowlevel/libusb/libusb.go:557:10: cannot define new methods on non-local type *C.struct_libusb_config_descriptor …
```

Update Dockerfile and fix Docker build failed

---

release/linux/Dockerfile.package
release/macos/Dockerfile
release/windows/Dockerfile
usb/lowlevel/libusb/libusb.go

Fix issue #297
**Solution:**
1. Fixed `libusb.go`. Golang 1.21 doesn't allow defining a method for non-local structs. The solution here is to create a type alias for used C interop structs. Then, we can define methods for these type aliases. For example, an alias for `C.struct_libusb_endpoint_descriptor` can be defined with `type Struct_Libusb_Endpoint_Descriptor = C.struct_libusb_endpoint_descriptor`.
2. The build release for macOS build failed because the `apple-codesign` need a newer version of cargo in the packaging Docker image. To resolve this, I update the Fedora version in the packaging Dockerfile to version 39.
I tested this using my Trezor model one is it's working great. Also, I tested the build release command and everything work fine now too.

Fix libusb and build release failed

---

usb/lowlevel/libusb/libusb.go

Fix for issue #303 
**Problem:**
Go version 1.24 doesn't allow defining a method for non-local structs including created structs with type aliases.
**Solution:**
The solution is to update the libusb's types from type aliases to type definitions. For example, `type Struct_Libusb_Endpoint_Descriptor = C.struct_libusb_endpoint_descriptor` is changed to `type Struct_Libusb_Endpoint_Descriptor C.struct_libusb_endpoint_descriptor`. However, this change prevents the defined types and the C interop types to be used interchangeably without the explicit type casting. As a result, we also needs to explicitly cast the variable types when the go codes interact with c codes. With these changes, I can build the project using go 1.24. It can be built with older go version as well.
I tested this with my …

Fix libusb build fail for golang >= 1.24
