usb/webusb.go

There is a bug in either libusb on windows or TREZOR T (Win)USB descriptors - maybe both - that makes TREZOR T to appear twice with the same path. One of the devices then fails to connect, and I don't know how to distinguish which one. (The user then sees an error message in 1/2 of cases)
Both libusb and TREZOR T USB code are very complex and I did not dare to edit either, but it was easy to fix it in bridge.
I am not sure how good idea it is though. I think this might introduce bugs much later (with some new interfaces, for example).

Correct windows libusb TREZOR T bugs

---

release/windows/Dockerfile.wdi_driver
release/windows/Makefile
release/windows/release.sh
release/windows/setupapi.patch
release/windows/trezord.nsis

Note - I have not yet tested the NSIS installer.
I *have* tested the build and the WDI tool on one Windows 7 computer. It is working and it is correctly installing the driver.
As I have noted privately, we will need to change VID and PID of webusb Trezor 1 (both BL and FW).

Add WDI WinUSB build + install

---

.travis.yml
README.md
release/linux/Makefile
release/macos/Makefile
release/windows/Makefile

I am not sure why we even added builds from github.com repo in the first place. :)
It is cleaner to build from local directory

Make all builds local

---

Gopkg.lock
usb/hidapi.go
usb/webusb.go
vendor/github.com/trezor/usbhid/hid.go

Using hid read timeouts, similar to webusb
Closing while reading caused crashes on windows. So I rewrote HID logic to copy webusb logic.
Now there is a lot of similar copypasted code, that could possibly be refactored

Hid read timeout

---

.travis.yml
server/api/api_test.go

Putting my money where my [mouth](https://github.com/trezor/trezord-go/issues/71) is - first testcases :)

tests: add tests for origin validation

---

release/windows/libwdi/examples/wdi-simple.c
release/windows/reinstall-drivers.bat
release/windows/trezord.nsis
server/status/status.go

Add libwdi log from the installer to the status log page, plus remove libwdi log from the status page textarea

Libwdi log

---

usb/lowlevel/c/libusb/os/windows_winusb.c

There are some issues with some very strange edge case that sometimes throws errors on reading drivers & GUIDs on composite device endpoints.
I want more information about what errors are being thrown out, so I added some more logs. This does not actually solve any issue, but might help us to see what the issue is.

windows: Add libusb composite debug logs

---

core/core.go
server/status/status.go
server/status/template.go
usb/hidapi.go
usb/udp.go
usb/webusb.go

Based on BcdDevice
Fixes https://github.com/trezor/trezord-go/issues/97
Depends on https://github.com/trezor/trezord-go/pull/70 (freebsd PR) since it touches the same places (I am using `freebsd` branch from this repo, not the one from the PR)

Display type on status page correctly

---

usb/lowlevel/c/hidapi/linux/hid.c
usb/lowlevel/c/libusb/io.c
usb/lowlevel/c/libusb/os/darwin_usb.c
usb/lowlevel/c/libusb/sync.c

Add some more debug messages into libusb for better debugging

libusb: Add more debug messages

---

README.md
core/core.go
server/api/api.go
wire/v1.go

api: New read command

---

README.md
core/core.go
memorywriter/memorywriter.go
server/api/api.go
trezord.go
usb/bus.go
usb/hidapi.go
usb/libusb.go
usb/udp.go

Add debuglink

---

core/core.go
trezord.go

debuglink: Reset option to prevent TTY reset on TT

---

core/core.go
memorywriter/memorywriter.go
server/api/api.go
server/http.go
server/status/status.go
server/status/windows.go
trezord.go
usb/hidapi.go
usb/libusb.go
usb/udp.go
wire/v1.go

golang can print stacktrace info well via runtime

debug: Remove manual function name from log

---

usb/libusb.go

Fixes https://github.com/trezor/trezord-go/issues/113

libusb: Better error when run in container

---

core/core.go
usb/libusb.go

Fixes #135
Please test, I don't have access to old BL :) also test if it doesn't break normal t1 devices and/or HID devices

linux: Fix old BL epOut

---

core/core.go
server/api/api.go

Solves https://github.com/trezor/trezord-go/issues/138

http: remove deprecated CloseNotifier

---

trezord.go
usb/hidapi_shim.go
usb/lowlevel/hidapi/wchar.go
usb/lowlevel/libusb/libusb.go

* Don't use custom patched libusb
* Build all of the shims/interfaces on OpenBSD

Add support for OpenBSD

---

.golangci.yml
core/core.go
core/core_test.go
server/api/api.go
server/api/api_test.go
trezord.go
usb/bus.go
usb/hidapi.go
usb/libusb.go
usb/lowlevel/hidapi/log.go
usb/lowlevel/hidapi/wchar.go
usb/lowlevel/libusb/libusb.go
usb/lowlevel/libusb/log.go
usb/udp.go

I followed the instructions given here to patch the code: https://travis-ci.org/github/trezor/trezord-go/jobs/741180592

Fix golangci-lint complaints

---

.gitlab-ci.yml
.golangci.yml
core/release.go
server/http.go
server/status/windows_shim.go
usb/hidapi.go
usb/lowlevel/hidapi/hid.go
usb/lowlevel/hidapi/wchar.go
usb/lowlevel/libusb/libusb.go

Also, remove ancient deprecated linters, plus linters, that are already in the default set.

Move to new golangci, fix issues

---

.github/workflows/check-go-validation.yml
usb/hidapi_shim.go

I have copied all from gitlab to github action. Also I fixed one lint issue that is only on Linux.
So far not adding the release builds, as they are not yet fixed for Linux/Windows.

Add github action lint

---

usb/hidapi.go

Remove trezorv2 from HIDAPI
